/* Generated by Convex (written to match `npx convex codegen`; it regenerates this). */
import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";
import { anyApi } from "convex/server";
import type * as community from "../community.js";

declare const fullApi: ApiFromModules<{ community: typeof community }>;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const api: FilterApi<typeof fullApi, FunctionReference<any, "public">> = anyApi as any;
