/* Generated by Convex (written to match `npx convex codegen`; it regenerates this). */
import type { DataModelFromSchemaDefinition } from "convex/server";
import type schema from "../schema.js";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
