/* Generated by Convex (written to match `npx convex codegen`; it regenerates this). */
import { mutationGeneric, queryGeneric } from "convex/server";
import type { MutationBuilder, QueryBuilder } from "convex/server";
import type { DataModel } from "./dataModel.js";

export const query: QueryBuilder<DataModel, "public"> = queryGeneric;
export const mutation: MutationBuilder<DataModel, "public"> = mutationGeneric;
